/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.mcreator.djmusicalanwalkerplaylist;

import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.common.registry.EntityEntry;
import net.minecraftforge.fml.common.network.simpleimpl.IMessageHandler;
import net.minecraftforge.fml.common.network.simpleimpl.IMessage;
import net.minecraftforge.fml.common.network.IGuiHandler;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.discovery.ASMDataTable;
import net.minecraftforge.fml.common.IWorldGenerator;
import net.minecraftforge.fml.common.IFuelHandler;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.client.event.ModelRegistryEvent;

import net.minecraft.world.storage.WorldSavedData;
import net.minecraft.world.gen.IChunkGenerator;
import net.minecraft.world.chunk.IChunkProvider;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.World;
import net.minecraft.util.ResourceLocation;
import net.minecraft.potion.Potion;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Item;
import net.minecraft.entity.player.EntityPlayerMP;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.block.Block;

import net.mcreator.djmusicalanwalkerplaylist.gui.GuiAlanWalkerPlaylistGUI;

import java.util.function.Supplier;
import java.util.Random;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class ElementsDjMusicAlanWalkerPlaylistMod implements IFuelHandler, IWorldGenerator {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<Biome>> biomes = new ArrayList<>();
	public final List<Supplier<EntityEntry>> entities = new ArrayList<>();
	public final List<Supplier<Potion>> potions = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();
	public ElementsDjMusicAlanWalkerPlaylistMod() {
		sounds.put(new ResourceLocation("dj_music_alan_walker_playlist", "awlily"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music_alan_walker_playlist", "awlily")));
		sounds.put(new ResourceLocation("dj_music_alan_walker_playlist", "aw_on_my_way"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music_alan_walker_playlist", "aw_on_my_way")));
		sounds.put(new ResourceLocation("dj_music_alan_walker_playlist", "aw_sky"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music_alan_walker_playlist", "aw_sky")));
		sounds.put(new ResourceLocation("dj_music_alan_walker_playlist", "aw_alone_pt_2"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music_alan_walker_playlist", "aw_alone_pt_2")));
		sounds.put(new ResourceLocation("dj_music_alan_walker_playlist", "aw_ignite"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music_alan_walker_playlist", "aw_ignite")));
		sounds.put(new ResourceLocation("dj_music_alan_walker_playlist", "alan_walker_-_alone_pt_1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music_alan_walker_playlist", "alan_walker_-_alone_pt_1")));
		sounds.put(new ResourceLocation("dj_music_alan_walker_playlist", "aw_diamond_heart"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music_alan_walker_playlist", "aw_diamond_heart")));
		sounds.put(new ResourceLocation("dj_music_alan_walker_playlist", "aw_all_falls_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music_alan_walker_playlist", "aw_all_falls_down")));
		sounds.put(new ResourceLocation("dj_music_alan_walker_playlist", "aw_force"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music_alan_walker_playlist", "aw_force")));
		sounds.put(new ResourceLocation("dj_music_alan_walker_playlist", "aw_tired"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music_alan_walker_playlist", "aw_tired")));
		sounds.put(new ResourceLocation("dj_music_alan_walker_playlist", "aw_play"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music_alan_walker_playlist", "aw_play")));
		sounds.put(new ResourceLocation("dj_music_alan_walker_playlist", "aw_unity"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music_alan_walker_playlist", "aw_unity")));
		sounds.put(new ResourceLocation("dj_music_alan_walker_playlist", "aw_hope"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music_alan_walker_playlist", "aw_hope")));
		sounds.put(new ResourceLocation("dj_music_alan_walker_playlist", "aw_hymn_for_the_weekend"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music_alan_walker_playlist", "aw_hymn_for_the_weekend")));
		sounds.put(new ResourceLocation("dj_music_alan_walker_playlist", "aw_memories"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music_alan_walker_playlist", "aw_memories")));
		sounds.put(new ResourceLocation("dj_music_alan_walker_playlist", "aw_stranger_things"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music_alan_walker_playlist", "aw_stranger_things")));
		sounds.put(new ResourceLocation("dj_music_alan_walker_playlist", "alan_walker_-_the_spectre"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music_alan_walker_playlist", "alan_walker_-_the_spectre")));
		sounds.put(new ResourceLocation("dj_music_alan_walker_playlist", "alan_walker_-_sing_me_to_sleep"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music_alan_walker_playlist", "alan_walker_-_sing_me_to_sleep")));
		sounds.put(new ResourceLocation("dj_music_alan_walker_playlist", "alan_walker_-_darkside_feat._au_ra_and_tomine_harket"),
				new net.minecraft.util.SoundEvent(
						new ResourceLocation("dj_music_alan_walker_playlist", "alan_walker_-_darkside_feat._au_ra_and_tomine_harket")));
		sounds.put(new ResourceLocation("dj_music_alan_walker_playlist", "alan_walker_-_faded"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music_alan_walker_playlist", "alan_walker_-_faded")));
	}

	public void preInit(FMLPreInitializationEvent event) {
		try {
			for (ASMDataTable.ASMData asmData : event.getAsmData().getAll(ModElement.Tag.class.getName())) {
				Class<?> clazz = Class.forName(asmData.getClassName());
				if (clazz.getSuperclass() == ElementsDjMusicAlanWalkerPlaylistMod.ModElement.class)
					elements.add((ElementsDjMusicAlanWalkerPlaylistMod.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(ElementsDjMusicAlanWalkerPlaylistMod.ModElement::initElements);
		this.addNetworkMessage(DjMusicAlanWalkerPlaylistModVariables.WorldSavedDataSyncMessageHandler.class,
				DjMusicAlanWalkerPlaylistModVariables.WorldSavedDataSyncMessage.class, Side.SERVER, Side.CLIENT);
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}

	@Override
	public void generate(Random random, int chunkX, int chunkZ, World world, IChunkGenerator cg, IChunkProvider cp) {
		elements.forEach(element -> element.generateWorld(random, chunkX * 16, chunkZ * 16, world, world.provider.getDimension(), cg, cp));
	}

	@Override
	public int getBurnTime(ItemStack fuel) {
		for (ModElement element : elements) {
			int ret = element.addFuel(fuel);
			if (ret != 0)
				return ret;
		}
		return 0;
	}

	@SubscribeEvent
	public void onPlayerLoggedIn(net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerLoggedInEvent event) {
		if (!event.player.world.isRemote) {
			WorldSavedData mapdata = DjMusicAlanWalkerPlaylistModVariables.MapVariables.get(event.player.world);
			WorldSavedData worlddata = DjMusicAlanWalkerPlaylistModVariables.WorldVariables.get(event.player.world);
			if (mapdata != null)
				DjMusicAlanWalkerPlaylistMod.PACKET_HANDLER.sendTo(new DjMusicAlanWalkerPlaylistModVariables.WorldSavedDataSyncMessage(0, mapdata),
						(EntityPlayerMP) event.player);
			if (worlddata != null)
				DjMusicAlanWalkerPlaylistMod.PACKET_HANDLER.sendTo(new DjMusicAlanWalkerPlaylistModVariables.WorldSavedDataSyncMessage(1, worlddata),
						(EntityPlayerMP) event.player);
		}
	}

	@SubscribeEvent
	public void onPlayerChangedDimension(net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerChangedDimensionEvent event) {
		if (!event.player.world.isRemote) {
			WorldSavedData worlddata = DjMusicAlanWalkerPlaylistModVariables.WorldVariables.get(event.player.world);
			if (worlddata != null)
				DjMusicAlanWalkerPlaylistMod.PACKET_HANDLER.sendTo(new DjMusicAlanWalkerPlaylistModVariables.WorldSavedDataSyncMessage(1, worlddata),
						(EntityPlayerMP) event.player);
		}
	}
	private int messageID = 0;
	public <T extends IMessage, V extends IMessage> void addNetworkMessage(Class<? extends IMessageHandler<T, V>> handler, Class<T> messageClass,
			Side... sides) {
		for (Side side : sides)
			DjMusicAlanWalkerPlaylistMod.PACKET_HANDLER.registerMessage(handler, messageClass, messageID, side);
		messageID++;
	}
	public static class GuiHandler implements IGuiHandler {
		@Override
		public Object getServerGuiElement(int id, EntityPlayer player, World world, int x, int y, int z) {
			if (id == GuiAlanWalkerPlaylistGUI.GUIID)
				return new GuiAlanWalkerPlaylistGUI.GuiContainerMod(world, x, y, z, player);
			return null;
		}

		@Override
		public Object getClientGuiElement(int id, EntityPlayer player, World world, int x, int y, int z) {
			if (id == GuiAlanWalkerPlaylistGUI.GUIID)
				return new GuiAlanWalkerPlaylistGUI.GuiWindow(world, x, y, z, player);
			return null;
		}
	}
	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<Biome>> getBiomes() {
		return biomes;
	}

	public List<Supplier<EntityEntry>> getEntities() {
		return entities;
	}

	public List<Supplier<Potion>> getPotions() {
		return potions;
	}
	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}
		protected final ElementsDjMusicAlanWalkerPlaylistMod elements;
		protected final int sortid;
		public ModElement(ElementsDjMusicAlanWalkerPlaylistMod elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLInitializationEvent event) {
		}

		public void preInit(FMLPreInitializationEvent event) {
		}

		public void generateWorld(Random random, int posX, int posZ, World world, int dimID, IChunkGenerator cg, IChunkProvider cp) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		public void registerModels(ModelRegistryEvent event) {
		}

		public int addFuel(ItemStack fuel) {
			return 0;
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
